# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
