# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0008_auto_20170905_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadfile',
        ),
    ]
