# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0009_delete_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='E:/tae/django/tbgoods/upload/%d')),
            ],
        ),
    ]
